[tools]
github-cli = "latest"
python = "3.14"
pre-commit = "latest"
node = "lts"
pnpm = "latest"
markdownlint-cli2 = "latest"

[settings]
experimental = true

[hooks]
enter = "bash ./scripts/enter_project.sh"

[env]
_.path = ['{{config_root}}/node_modules/.bin']
_.file = '.env'

[tasks.dev]
description = "Dev Mode"
run = "astro dev --host 0.0.0.0"
